/**
 * Nairobi pickup/return locations
 * Business operates within Nairobi only.
 * Used when admin adds a car (pick location) and when client books (pickup/return).
 */
const NAIROBI_LOCATIONS = [
    'Bahati',
    'Buruburu',
    'Dagoretti',
    'Dandora',
    'Donholm',
    'Eastleigh',
    'Embakasi',
    'Embakasi Pipeline',
    'Gigiri',
    'JKIA Airport',
    'Wilson Airport',
    'Kahawa',
    'Kahawa Sukari',
    'Kahawa Wendani',
    'Kahawa West',
    'Kaloleni',
    'Kambi Muru',
    'Kamulu',
    'Kamukunji',
    'Kangemi',
    'Karen',
    'Kariobangi',
    'Kasarani',
    'Kawangware',
    'Kayole',
    'Kiambiu',
    'Kibera',
    'Kichinjio',
    'Kikuyu',
    'Kileleshwa',
    'Kilimani',
    'Kisumu Ndogo',
    'Kitisuru',
    'Komarock',
    'Korogocho',
    'Kware',
    'Kyuna',
    'Lang\'ata',
    'Lavington',
    'Loresho',
    'Lower Kabete',
    'Makadara',
    'Mathare',
    'Matasia',
    'Mihango',
    'Muthaiga',
    'Nairobi CBD',
    'Nairobi West',
    'Ng\'ando',
    'Ngara',
    'Ngong',
    'Njiru',
    'Nyari',
    'Nyayo Estate',
    'Nyayo Highrise',
    'Ongata Rongai',
    'Pangani',
    'Parklands',
    'Ridgeways',
    'Rosslyn',
    'Roysambu',
    'Ruaka',
    'Ruiru',
    'Runda',
    'Riverside',
    'Spring Valley',
    'Starehe',
    'Syokimau',
    'Thika Road',
    'Umoja',
    'Upper Hill',
    'Utawala',
    'Uthiru',
    'Westlands',
    'Industrial Area',
    'Hurlingham',
    'South C',
    'South B'
].sort();

module.exports = { NAIROBI_LOCATIONS };
